services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: udemy_devops
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ./services/auth-service/.env

  api-gateway:
    build: ./gateway
    ports:
      - "8080:80"
    depends_on:
      - auth-service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - auth-service

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9101:9100"

volumes:
  pgdata:
