services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: udemy_devops
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    ports:
      - "33000:3000"
    depends_on:
      - postgres
    env_file:
      - ./services/auth-service/.env

  api-gateway:
    image: nginx
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "38080:80"
    depends_on:
      - auth-service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "39090:9090"
    depends_on:
      - auth-service

  grafana:
    image: grafana/grafana
    ports:
      - "33001:3000"
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    ports:
      - "39100:9100"

volumes:
  pgdata:
